# Generated by Django 4.0.1 on 2023-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_email_contact_email12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email12',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message12',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name12',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sub12',
            new_name='sub',
        ),
    ]
