# Generated by Django 4.0.1 on 2023-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email12_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name32', models.CharField(max_length=30)),
                ('email32', models.EmailField(max_length=254)),
                ('sub32', models.CharField(max_length=100)),
                ('message32', models.TextField()),
            ],
        ),
    ]
